services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - .env
    volumes:
      - test_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"           # ★あとで Cloud Run 固定 IP だけに絞る
volumes:
  test_pg_data: